ALTER TABLE businesses
  ADD COLUMN IF NOT EXISTS phone      TEXT,
  ADD COLUMN IF NOT EXISTS website    TEXT,
  ADD COLUMN IF NOT EXISTS instagram  TEXT,
  ADD COLUMN IF NOT EXISTS menu_url   TEXT,
  ADD COLUMN IF NOT EXISTS hours      TEXT,
  ADD COLUMN IF NOT EXISTS discounts  TEXT;
